// database
pub const D: u32 = 16;
pub const TEST_DATA: [u16; 4] = [
    0xdead,
    0xbeef,
    0xdaad,
    0xeebe,
];
pub const LOG_DATA_LEN: u32 = TEST_DATA.len().ilog2();

// DP constant
// Generated by setting epsilon to 1 and delta to 1/n^(log n)
pub const N: usize = 8 * ((LOG_DATA_LEN * LOG_DATA_LEN) + 1) as usize;

// monomial limit
pub const K: u32 = 2;
pub const NUM_COEFFICIENTS: usize = 16;

pub const PROVER_ADDRESS: &str = "127.0.0.1";
pub const PROVER_PORT: &str = "10020";
